# S02 T04: Pràctica amb programació numèrica

### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error

In [1]:
import numpy as np
def arrayInfo(a):
    print("Suma números del array: ",a.sum()) 
    print("Numero más pequeño del array: ",a.min())
    print("Numero más grande del array: ",a.max(axis=0) )
    print("Media: ",a.mean() )
    print("Desviación estandar: ",np.std(a) )
    
x = input("Escriu un array de números: ")
b = x.split()
c = np.array(b)
c = np.array(list(map(np.int, c)))
arrayInfo(c)

Escriu un array de números: 5 6 78 45 3 28 0 12 7 34
Suma números del array:  218
Numero más pequeño del array:  0
Numero más grande del array:  78
Media:  21.8
Desviación estandar:  23.578804040917767


### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [2]:
def matrixRandom(k):
    random_matrix_array = np.random.randint(0,100,size=(k,k))
    return random_matrix_array

num = input("Escribe el tamaño de la matriz: ")
num = int(num)
print(matrixRandom(num))


Escribe el tamaño de la matriz: 5
[[ 1 98 79 76 31]
 [49 41 24 63 43]
 [45 93 34 64 76]
 [33 76 35 21 71]
 [74 36  6 97 22]]


### Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [3]:
def op(mat):
    fila = 0
    for i in mat:
        sumCol = 0
        sumFila = 0
        col = 0
        for j in i:
            sumFila += mat[fila][col] 
            sumCol += mat[col][fila] 
            col += 1
            
        fila += 1
        print("Fila {}: {}".format(fila,sumFila)) 
        print("Columna {}: {}".format(fila,sumCol)) 

            
num = input("Escribe el tamaño de la matriz: ")
num = int(num)
mat = matrixRandom(num)
print(mat)
op(mat)

Escribe el tamaño de la matriz: 4
[[73 10 88 45]
 [24 29 67 38]
 [27 44 35 71]
 [84 67 23 94]]
Fila 1: 216
Columna 1: 208
Fila 2: 158
Columna 2: 150
Fila 3: 177
Columna 3: 213
Fila 4: 268
Columna 4: 248


### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [4]:
var1 = np.random.randint(0, 10, 50)
var2 = var1 + np.random.normal(0, 10, 50)
print(var1)
print(var2)
np.corrcoef(var1, var2)

[0 5 3 4 6 2 5 6 3 2 1 0 4 1 4 3 6 8 9 8 1 5 7 3 0 1 1 8 2 9 5 6 4 0 6 0 8
 3 1 0 5 6 7 2 4 5 6 3 5 9]
[  3.66151333   4.3916454    2.45322717  10.79298957   2.13364346
   9.55828874   5.79611547  -4.97910134  -8.86297997  -5.9018881
   0.23205621  -6.35985307   7.46906841   4.79338677  -6.56216513
   4.40660029   8.35443385   6.59042223  12.26610395  13.8165105
 -15.00948029   0.75500885  11.24356693   5.37485638  -9.11951193
 -21.13782754  -0.05798787 -17.60705115  -5.14447591  14.72771391
   2.9767303   18.29204486 -15.17325417  -1.40765049   1.60884786
 -15.68878902  -2.19927466 -12.47294547  -5.10522683   6.47985692
  14.17262801   7.46735551  13.76026776  -2.20210299  16.46116563
   0.1389355   -1.57300269   2.08257215  25.76654088  26.8854179 ]


array([[1.        , 0.47690333],
       [0.47690333, 1.        ]])